version: '3'

services:
    app:
        build: .
        image: blog
        container_name: blog
        ports:
            - 3000:3000
        command: bash entrypoint.sh
        volumes:
            - .:/home/app
            - /home/app/node_modules
